# Hybrid Models for Recommendation Systems

Load Pandas, we are going to need it for manipulating data

In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

Now load the data

In [2]:
user_ratings_df = pd.read_csv("user_ratings.csv")
user_features_df = pd.read_csv("user_features.csv")
item_features_df = pd.read_csv("item_features.csv")

In [3]:
print(user_ratings_df)

   The Call of Cthulhu   Frankenstein   Dracula   Neuromancer   Space Odyssey
0                  8.0            2.0       NaN           5.0             4.0
1                  3.0            2.0       NaN           7.0             7.0
2                  9.0            NaN       7.0           8.0             5.0
3                  NaN            NaN       7.0           8.0             9.0
4                  NaN            1.0       8.0           3.0             7.0
5                  2.0            3.0       5.0           NaN             NaN
6                  4.0            2.0       NaN           2.0             7.0
7                  7.0            1.0       2.0           7.0             9.0
8                  3.0            3.0       NaN           7.0             3.0
9                  4.0            NaN       5.0           3.0             3.0


In [4]:
print(user_features_df)

   Sex   Over60
0  1.0      0.0
1  0.0      1.0
2  0.0      0.0
3  1.0      0.0
4  0.0      1.0
5  0.0      0.0
6  0.0      0.0
7  1.0      0.0
8  0.0      1.0
9  1.0      0.0


In [5]:
print(item_features_df)

   Critic0   Critic1
0      0.3       0.9
1      0.9       0.3
2      0.6       0.4
3      0.2       0.1
4      0.7       0.8


In [6]:
user_features_df["key"] = 0
user_features_df["user_id"] = range(0,user_features_df.shape[0])
item_features_df["key"] = 0
item_features_df["item_id"] = range(0,item_features_df.shape[0])

merged_df = pd.merge(user_features_df,    item_features_df,left_index=True,on="key")
merged_df[["item_id", "user_id"]]




merged_df["rating"] = list(map(lambda ids: user_ratings_df.values[ids[1]][ids[2]], 
                          merged_df[["user_id", "item_id"]].itertuples()))

In [7]:
merged_df

Sex   Over60  key  user_id  Critic0   Critic1  item_id  rating
0  1.0      0.0    0        0      0.3       0.9        0     8.0
1  1.0      0.0    0        0      0.9       0.3        1     2.0
2  1.0      0.0    0        0      0.6       0.4        2     NaN
3  1.0      0.0    0        0      0.2       0.1        3     5.0
4  1.0      0.0    0        0      0.7       0.8        4     4.0
0  0.0      1.0    0        1      0.3       0.9        0     3.0
1  0.0      1.0    0        1      0.9       0.3        1     2.0
2  0.0      1.0    0        1      0.6       0.4        2     NaN
3  0.0      1.0    0        1      0.2       0.1        3     7.0
4  0.0      1.0    0        1      0.7       0.8        4     7.0
0  0.0      0.0    0        2      0.3       0.9        0     9.0
1  0.0      0.0    0        2      0.9       0.3        1     NaN
2  0.0      0.0    0        2      0.6       0.4        2     7.0
3  0.0      0.0    0        2      0.2       0.1        3     8.0
4  0.0      0.0    0        2      0.7       0.8        4     5.0
0  1.0      0.0    0        3      0.3       0.9        0     NaN
1  1.0      0.0    0        3      0.9       0.3        1     NaN
2  1.0      0.0    0        3      0.6       0.4        2     7.0
3  1.0      0.0    0        3      0.2       0.1        3     8.0
4  1.0      0.0    0        3      0.7       0.8        4     9.0
0  0.0      1.0    0        4      0.3       0.9        0     NaN
1  0.0      1.0    0        4      0.9       0.3        1     1.0
2  0.0      1.0    0        4      0.6       0.4        2     8.0
3  0.0      1.0    0        4      0.2       0.1        3     3.0
4  0.0      1.0    0        4      0.7       0.8        4     7.0
0  0.0      0.0    0        5      0.3       0.9        0     2.0
1  0.0      0.0    0        5      0.9       0.3        1     3.0
2  0.0      0.0    0        5      0.6       0.4        2     5.0
3  0.0      0.0    0        5      0.2       0.1        3     NaN
4  0.0      0.0    0        5      0.7       0.8        4     NaN
0  0.0      0.0    0        6      0.3       0.9        0     4.0
1  0.0      0.0    0        6      0.9       0.3        1     2.0
2  0.0      0.0    0        6      0.6       0.4        2     NaN
3  0.0      0.0    0        6      0.2       0.1        3     2.0
4  0.0      0.0    0        6      0.7       0.8        4     7.0
0  1.0      0.0    0        7      0.3       0.9        0     7.0
1  1.0      0.0    0        7      0.9       0.3        1     1.0
2  1.0      0.0    0        7      0.6       0.4        2     2.0
3  1.0      0.0    0        7      0.2       0.1        3     7.0
4  1.0      0.0    0        7      0.7       0.8        4     9.0
0  0.0      1.0    0        8      0.3       0.9        0     3.0
1  0.0      1.0    0        8      0.9       0.3        1     3.0
2  0.0      1.0    0        8      0.6       0.4        2     NaN
3  0.0      1.0    0        8      0.2       0.1        3     7.0
4  0.0      1.0    0        8      0.7       0.8        4     3.0
0  1.0      0.0    0        9      0.3       0.9        0     4.0
1  1.0      0.0    0        9      0.9       0.3        1     NaN
2  1.0      0.0    0        9      0.6       0.4        2     5.0
3  1.0      0.0    0        9      0.2       0.1        3     3.0
4  1.0      0.0    0        9      0.7       0.8        4     3.0

In [8]:
train = merged_df.dropna()
test = merged_df[merged_df.isnull().any(axis=1)]
#print(test.to_latex())

In [13]:
 train.head(), test.head()

(   Sex   Over60  key  user_id  Critic0   Critic1  item_id  rating
 0  1.0      0.0    0        0      0.3       0.9        0     8.0
 1  1.0      0.0    0        0      0.9       0.3        1     2.0
 3  1.0      0.0    0        0      0.2       0.1        3     5.0
 4  1.0      0.0    0        0      0.7       0.8        4     4.0
 0  0.0      1.0    0        1      0.3       0.9        0     3.0,
    Sex   Over60  key  user_id  Critic0   Critic1  item_id  rating
 2  1.0      0.0    0        0      0.6       0.4        2     NaN
 2  0.0      1.0    0        1      0.6       0.4        2     NaN
 1  0.0      0.0    0        2      0.9       0.3        1     NaN
 0  1.0      0.0    0        3      0.3       0.9        0     NaN
 1  1.0      0.0    0        3      0.9       0.3        1     NaN)

In [14]:
n_latent_features = 2

user_ratings = user_ratings_df.values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_latent_features))

In [47]:
user_features = user_features_df.values
item_features = item_features_df.values

I have observed that "user_features" and "item_features" contains two extra columns where we created above not necessary for modelling

In [48]:
new_user_features = user_features[:,:2]
new_item_features = item_features[:, :2]

In [52]:
new_user_features

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [53]:
print(new_user_features.shape), 
print(new_item_features.shape)

(10, 2)
(5, 2)


In [54]:
user_features = np.concatenate([np.ones(shape = (new_user_features.shape[0],1)), new_user_features], axis = 1)
item_features = np.concatenate([np.ones(shape = (new_item_features.shape[0],1)), new_item_features], axis = 1)


user_features_weights = np.random.random((user_ratings.shape[0], user_features.shape[1] ))
item_features_weights = np.random.random((user_ratings.shape[1], item_features.shape[1] ))

In [55]:
print(user_features.shape)
print(item_features.shape)
print(user_features_weights.shape)
print(item_features_weights.shape)

(10, 3)
(5, 3)
(10, 3)
(5, 3)


In [56]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    
    user_score = user_features_weights[user_id].dot(user_features[user_id])
    item_score = item_features_weights[item_id].dot(item_features[item_id])
    #print user_preference.dot(item_preference), user_score, item_score
    return user_preference.dot(item_preference) + user_score + item_score

def train(user_id, item_id, rating,alpha = 0.001, 
                                   latent_feature_weight_decay = 0.1, 
                                   user_weight_decay = 0.01,
                                   item_weight_decay = 0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating - rating );
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err *  ( latent_item_features[item_id] + latent_feature_weight_decay*latent_user_preferences[user_id])
    latent_item_features[item_id] -= alpha * err * ( user_pref_values + latent_feature_weight_decay*latent_item_features[item_id])
    
    user_features_weights[user_id] -=alpha * err *(  user_features[user_id] + user_weight_decay* user_features_weights[user_id])
    item_features_weights[item_id] -=alpha * err * ( item_features_weights[item_id] + item_weight_decay* item_features_weights[item_id])
    
    
    return err
    


def sgd(iterations = 30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if(not np.isnan(rating)):
                    err = train(user_id,item_id,rating)
                    error.append(err)
    mse = (np.array(error) ** 2).mean()          
    print(mse)
                    
                    
    
                    
                    
    


In [58]:
for _ in range(0,10): 
    sgd()

0.2876347777844631
0.2815506870349437
0.27852816634846533
0.2766712503531902
0.2753945410625571
0.2744531415074943
0.273725039653807
0.27314203761579237
0.27266276410801427
0.27226053200739875


In [60]:
predictions = np.zeros(shape = (latent_user_preferences.shape[0], latent_item_features.shape[0]) )
#print latent_user_preferences
print(user_features_weights)
print(item_features_weights)
for user_id in range(0, latent_user_preferences.shape[0]):
            for item_id in range(0, latent_item_features.shape[0]):
                predictions[user_id,item_id] =  predict_rating(user_id,item_id)

[[-0.973 -0.627  0.621]
 [ 3.727  0.549  2.891]
 [ 3.613  0.605  0.85 ]
 [ 1.698  2.004  0.469]
 [-0.343  0.338 -0.069]
 [ 0.108  0.825  0.735]
 [-0.79   0.326  0.554]
 [ 0.257  0.944  0.497]
 [ 3.251  0.87   3.54 ]
 [-0.583 -0.538  0.242]]
[[7.143e-01 1.974e+00 2.883e+00]
 [1.835e-01 1.301e-01 9.775e-01]
 [5.498e+00 1.280e+00 2.226e+01]
 [2.697e+00 5.105e+00 2.386e+00]
 [1.238e-02 1.823e-02 3.708e-02]]


In [62]:
values = [zip(user_ratings[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = user_ratings_df.columns
comparison_data#.applymap(lambda (x,y): "(%2.3f|%2.3f)"%(x,y))

The Call of Cthulhu                Frankenstein  \
0   (8.0, 7.928066568852985)   (2.0, 2.2785600637387304)   
1   (3.0, 2.895605785930566)    (2.0, 2.463938020611332)   
2    (9.0, 8.84693703083039)    (nan, 4.983630367135537)   
3   (nan, 9.076233235337638)    (nan, 5.011848084431944)   
4   (nan, 4.475660637288097)   (1.0, 0.5145766507274315)   
5   (2.0, 2.015058498019973)   (3.0, 2.9849115454426203)   
6  (4.0, 4.4189154790875715)  (2.0, 0.32136627292319164)   
7   (7.0, 6.928515005409684)   (1.0, 2.6371529467927326)   
8  (3.0, 3.0599040818843206)   (3.0, 2.7895398276287784)   
9  (4.0, 3.9055441259287833)  (nan, 0.01707061635791196)   

                     Dracula                Neuromancer  \
0  (nan, -36.25030404913861)  (5.0, 4.7988858174296265)   
1   (nan, 91.68299643632389)   (7.0, 6.648994752654915)   
2    (7.0, 6.99349432796676)   (8.0, 8.145467915173601)   
3  (7.0, 6.9998469269005845)   (8.0, 7.999568774562889)   
4   (8.0, 7.996447242844767)  (3.0, 3.4687366845254344)   
5    (5.0, 5.00043346967389)  (nan, 10.343518691314344)   
6   (nan, 4.796645636527536)  (2.0, 3.2244831841633532)   
7  (2.0, 2.0075036402926223)   (7.0, 5.486507790090062)   
8   (nan, 90.65540896276678)   (7.0, 7.145025902740515)   
9   (5.0, 4.995951417610499)  (3.0, 3.0904403708634653)   

               Space Odyssey  
0    (4.0, 3.99530123774104)  
1   (7.0, 6.990858694029768)  
2   (5.0, 5.012888869795482)  
3   (9.0, 9.000088440993752)  
4   (7.0, 7.018804632046588)  
5  (nan, -92.57609429650446)  
6   (7.0, 7.029668060882161)  
7   (9.0, 8.942466558454322)  
8  (3.0, 3.0030757042004304)  
9    (3.0, 3.00799066413215)

In [64]:
#comparison_data

In [66]:
d = comparison_data.to_latex()
text_file = open("comparison_hybrid.txt", "w")
text_file.write(d)
text_file.close()